BaSP-TG-21: admin form
BaSP-m2022/balti-trackgenix-app pull request #10
Opened 2022-05-31 22:29 UTC by lautaro23

-App conected to data base
-Form component developed
-Post and Put logic developed

2022-06-02 02:09 UTC, GonzaloBracamonte reviewed
El codigo se ve bien pero el boton de borrar no funciona y el Put crea un nuevo item aunque esten todos casi los campos vacios, revisa que haya alguna validacion

2022-06-02 02:37 UTC, MatiasJoaquinReynoso requested changes
Metodo POST funciona correctamente pero el metodo PUT al clickear en boton edit me redirecciona a la pagina para crear admin (add admin)

2022-06-02 12:55 UTC, lautaro23 commented
Ahi actualice el required! Me olvide de aclarar que el create se utiliza tanto para post como para put. cambie el nombre del boton a save admin

2022-06-02 14:18 UTC, negrojcb approved these changes

2022-06-02 16:07 UTC, MatiasJoaquinReynoso commented
> lauti justo te iba a comentar por slack pero bueno te lo dejo acá también.
> 
> 1. Método POST anda todo bien salvo el boolean isActive
>    lo que apunto es:
>    a) Si te pidieron que todos los admins sean activos entonces yo diria que tu checkbox esta perfecto porque tienen q ir si o si clickeados en isactive (aca entonces estaria perfecto tu metodo POST por q estaria todo OK)
>    b) Si te pidieron que el admin al crearse pueda elegir entre true o false en el isactive tendrias q corregirlo porq siempre te van a salir activos
> 2. Método PUT el button edit me redirecciona a la seccion de add admin

Se charlo y revisaron los metodos con Lauti:
1) Metodo POST anda todo lo esperado por el asi q anda bien
2) Metodo PUT lo mismo se edita correctamente

2022-06-02 18:07 UTC, FranGutierrez approved these changes

2022-06-02 18:10 UTC, MatiasJoaquinReynoso approved these changes

2022-06-02 23:06 UTC, merged

2022-06-04 02:02 UTC, BaltazarCortina1 commented on src/Components/Admins/index.js
> +    setAdmins([...admins, newAdmin]);
En este caso `newAdmin` es exactamente lo mismo que `adm`

2022-06-04 02:03 UTC, BaltazarCortina1 commented on src/Components/Admins/index.js
> +        <button onMouseDown={() => changeScreen(true)}>Save Admin</button>
Seria mejor que sean `onClick`

2022-06-04 02:04 UTC, BaltazarCortina1 commented on src/Components/Admins/Form/index.js
> +      console.log(data);
Este console.log no deberia estar