BaSP-TG-35: Sidebar shared component
BaSP-m2022/balti-trackgenix-app pull request #18
Opened 2022-06-04 19:41 UTC by Julian25

- Sidebar shared component added
- Sidebar styles according to figma added
- Sidebar implemented in layout

2022-06-04 20:59 UTC, lautaro23 commented on src/Components/Shared/Sidebar/sidebar.module.css
> +}
solo falta este espacio juli

2022-06-04 20:59 UTC, lautaro23 commented on src/Components/Layout/layout.module.css
>  }
también falta un espacio.

2022-06-04 20:59 UTC, lautaro23 approved these changes

2022-06-05 14:16 UTC, CorinaArreguez requested changes
Cambiar el nombre de los archivos a index.jsx, index.module.css

2022-06-05 14:24 UTC, FranGutierrez approved these changes

2022-06-05 16:01 UTC, CorinaArreguez approved these changes

2022-06-05 17:21 UTC, merged

2022-06-13 04:24 UTC, BaltazarCortina1 commented on src/Components/Layout/index.js
> +import Sidebar from '../Shared/Sidebar/index';
El index aca no es necesario