BaSP-TG-32: Modal component created and styled. Pending implementation
BaSP-m2022/balti-trackgenix-app pull request #20
Opened 2022-06-05 20:48 UTC by FedeBrus64

This component works the following way:
- First, it receives a function, called handleClose(), you must pass it a boolean to toggle the modal show/hide
- A boolean variable, isOpen. If true, the modal will show
- Children, which is the internal part of the modal. Here is where you put everything the modal will show (I did not put accept/cancel buttons, since the modal could be for confirming an action or just notifying something)

The implementation has not been made yet, but you can use this in your index for it to show:
- First, paste this in the declarations: const [isAdding, setIsAdding] = useState(false);
- Then, in the return part of the function in your index file, paste this:
<Modal
        handleClose={() => {
          setIsAdding(false);
        }}
        isOpen={isAdding}
      >
        children
      </Modal>
- Replace 'children' with what you want the modal to show

2022-06-05 23:21 UTC, lautaro23 commented on src/Components/Shared/Select/Select.jsx
> +export default Select;
agregar un espacio despues del export default.

2022-06-05 23:31 UTC, lautaro23 approved these changes

2022-06-07 01:42 UTC, FedeBrus64 commented on src/Components/Shared/Select/Select.jsx
> +export default Select;
Corrected!

2022-06-08 18:40 UTC, BaltazarCortina1 requested changes

2022-06-08 18:40 UTC, BaltazarCortina1 commented on src/Components/Shared/Modal/Modal.jsx
> +  }
Esto es practicamente el mismo codigo en ambos casos. Se podria dejar una sola vez y agregar solo lo que falta cuando `isConfirmation` sea `true`.

2022-06-09 14:31 UTC, Julian25 approved these changes

2022-06-09 18:45 UTC, CorinaArreguez approved these changes

2022-06-09 19:31 UTC, BaltazarCortina1 approved these changes

2022-06-09 19:34 UTC, merged

2022-06-13 01:12 UTC, BaltazarCortina1 commented on src/Components/Shared/Modal/Index.jsx
> +  }
Esto es practicamente el mismo codigo. Deberia estar solo una vez, y cambiar los botones en funcion de si isConfirmation es true o no

2022-06-13 01:13 UTC, BaltazarCortina1 commented on src/Components/Shared/Modal/Index.jsx
> +import React from 'react';
El nombre de este archivo deberia ser `index.jsx`, con minuscula