BaSP-TG-34: Select and input components
BaSP-m2022/balti-trackgenix-app pull request #21
Opened 2022-06-05 20:57 UTC by FedeBrus64

This components work the following way:
- They receive the following properties: id, required, value; to set them on the html part of the components (Input also receives the type of the data introduced, i.e. text, number, etc).
- There is also a text property, to set the text that the label will show before the input/select.

This components have not yet been implemented. Make sure to let me know if something is not working as it should.

2022-06-07 03:03 UTC, Julian25 approved these changes
Excellente job!!

2022-06-07 03:23 UTC, CorinaArreguez approved these changes

2022-06-08 18:49 UTC, BaltazarCortina1 requested changes

2022-06-08 18:49 UTC, BaltazarCortina1 commented on src/Components/Shared/Input/Input.jsx
> +      ></input>
La etiqueta de cierre no es necesaria. Podes poner `/>` en la misma etiqueta de apertura

2022-06-08 18:49 UTC, BaltazarCortina1 commented on src/Components/Shared/Input/Input.jsx
> +import React from 'react';
Cambiar los nombres de los archivos a index

2022-06-08 18:49 UTC, BaltazarCortina1 commented on src/Components/Shared/Select/Select.jsx
> +        {options}
Aca falta hacer los cambios que hablamos en la pre-entrega para adaptarlo al componente form

2022-06-08 18:49 UTC, BaltazarCortina1 commented on src/Components/Shared/Modal/Modal.jsx
> +import React from 'react';
Elimina el componente Modal de esta branch asi podemos mergearlo por separado

2022-06-09 18:05 UTC, lautaro23 approved these changes

2022-06-09 19:32 UTC, BaltazarCortina1 approved these changes

2022-06-09 19:38 UTC, merged