BaSP-TG-37: super admin list
BaSP-m2022/balti-trackgenix-app pull request #27
Opened 2022-06-07 23:08 UTC by GonzaloBracamonte

- [ ] Use button component in Super Admin.

- [ ] Use list component in Super Admin.

- [ ] Use modal component in Super Admin.

- [ ] Validate that the back response is successful before saving the data.

- [ ] Remove import React from 'react' when this component is not used

- [ ] Set list and seperate form on different screens.

- [ ] The function inside use efect cannot be anynchronous

2022-06-08 16:58 UTC, FranGutierrez requested changes

2022-06-08 16:58 UTC, FranGutierrez commented on src/Components/SuperAdmins/index.js
> +  useEffect(() => {
Manejar el fetch con un try catch en una función async externa al useEffect, en el useEffect ejecutar dicha función

2022-06-08 17:03 UTC, FranGutierrez commented on src/Components/SuperAdmins/index.js
> +  useEffect(() => {
De la siguiente forma por ejemplo en el recurso de timesheet:
const fetchTimeSheet = async () => {
    try {
      const response = await fetch(`${process.env.REACT_APP_API_URL}/${resource}`);
      const jsonResponse = await response.json();
      setTimeSheets(jsonResponse.data);
      setIsLoading(false);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error(error);
    }
  };

  useEffect(async () => {
    fetchTimeSheet();
    formatDataOptions();
  }, []);

2022-06-09 02:24 UTC, FranGutierrez approved these changes

2022-06-09 19:06 UTC, negrojcb approved these changes

2022-06-10 21:09 UTC, merged

2022-06-13 02:01 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/index.js
> +import React, { useState, useEffect } from 'react';
Deberias haber eliminado este archivo

2022-06-13 02:30 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/index.js
> +  const config = [
Faltan los ultimos cambios para adaptar la implementacion al nuevo Form