BaSP-TG-42: form implemented
BaSP-m2022/balti-trackgenix-app pull request #28
Opened 2022-06-08 02:14 UTC by Julian25

Work done on this branch:

- Implemented form component in Super Admin
- Implemented Modal component in Super Admin
- Implemented Button component in Super Admin

2022-06-08 17:10 UTC, FranGutierrez requested changes

2022-06-08 17:10 UTC, FranGutierrez commented on src/Components/SuperAdmins/index.js
>        const response = await fetch(`${process.env.REACT_APP_API_URL}/super-admin`);
Manejar el fetch y useEffect de esta forma, ejemplo del recurso de timesheets:
const fetchTimeSheet = async () => {
    try {
      const response = await fetch(`${process.env.REACT_APP_API_URL}/${resource}`);
      const jsonResponse = await response.json();
      setTimeSheets(jsonResponse.data);
      setIsLoading(false);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error(error);
    }
  };

  useEffect(async () => {
    fetchTimeSheet();
    formatDataOptions();
  }, []);

2022-06-08 21:07 UTC, FranGutierrez approved these changes
Approved!

2022-06-08 23:52 UTC, negrojcb approved these changes

2022-06-09 00:10 UTC, MatiasJoaquinReynoso approved these changes
Everything work OK !

2022-06-10 20:20 UTC, merged

2022-06-13 04:25 UTC, BaltazarCortina1 commented on src/Components/Shared/Input/Input.jsx
> +import React from 'react';
Estos archivos quedaron repetidos con distinto nombre

2022-06-13 04:27 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/List/super-admins.module.css
> +h2 {
No hay que usar selectores que empiecen con elementos html porque afectan a toda la app, no solo al componente.

2022-06-13 04:28 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/List/index.jsx
> +      saveSuperadmins(body.data);
Sigue faltando validar la respuesta.

2022-06-13 04:29 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/Form/index.jsx
> +  const [isAdding, setIsAdding] = useState(false);
Este state solo lo usas para mostrar el modal, no se deberia llamar showModal o algo asi?

2022-06-13 04:30 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/Form/index.jsx
> +        saveSuperadmins(body.data);
Sigue faltando validar la respuesta.