BaSP-TG-42: Project - Form implemented
BaSP-m2022/balti-trackgenix-app pull request #29
Opened 2022-06-08 02:26 UTC by lautaro23

Work done on this branch:

Implemented form component in Project
Implemented Loading component in Project
Implemented Button component in Project

2022-06-08 17:17 UTC, FranGutierrez requested changes

2022-06-08 21:10 UTC, FranGutierrez approved these changes

2022-06-11 21:34 UTC, Julian25 approved these changes

2022-06-11 21:40 UTC, negrojcb approved these changes

2022-06-11 21:42 UTC, merged

2022-06-13 04:42 UTC, BaltazarCortina1 commented on src/Components/Projects/List/index.jsx
> +      setProjects(jsonResponse.data);
Sigue faltando validar la respuesta.

2022-06-13 04:43 UTC, BaltazarCortina1 commented on src/Components/Projects/Form/index.jsx
> +  const [isAdding, setIsAdding] = useState(false);
Este state solo lo usas para mostrar el modal, no se deberia llamar showModal o algo asi?

2022-06-13 04:46 UTC, BaltazarCortina1 commented on src/Components/Projects/Form/index.jsx
> +        setProject(projectFormatted);
Sigue faltando validar la respuesta.

2022-06-13 04:51 UTC, BaltazarCortina1 commented on src/Components/Projects/Form/index.jsx
> +    });
Esto lo podrias hacer cuando declaras data directamente.
`employees: [{ employeeId: project.employees, ... }]`

2022-06-13 04:54 UTC, BaltazarCortina1 commented on src/Components/Projects/List/index.jsx
> +          : '',
`employeeId` no existe dentro de `project`. La prop es `employes` y es un array, asi que tenes que agarrar el primer elemento.

2022-06-13 04:55 UTC, BaltazarCortina1 commented on src/Components/Projects/Form/index.jsx
> +    });
Aca vendria mejor un map en lugar de un forEach, asi no hace falta que declares el array vacio antes y que vayas pusheando los elementos