BaSP-TG-13: super admin list
BaSP-m2022/balti-trackgenix-app pull request #3
Opened 2022-05-31 03:07 UTC by CorinaArreguez

- [ ] Connect app to server.
- [ ] Develop list component.
- [ ] Logic for get method.
- [ ] Logic for delete method.

2022-05-31 12:27 UTC, FranGutierrez requested changes

2022-05-31 12:27 UTC, FranGutierrez commented on src/Components/SuperAdmins/ListItem/SuperAdmin.jsx
> +    deleteItem(listItem._id);
Te faltó hacer el fetch del metodo DELETE para eliminar el super admin del servidor y no solo de la lista

2022-05-31 23:17 UTC, FranGutierrez approved these changes

2022-05-31 23:50 UTC, MatiasJoaquinReynoso approved these changes
Hola Corina testie esta PR y funciona todo OK 👍

2022-06-01 16:02 UTC, MatiasJoaquinReynoso approved these changes
Keep working everything OK !!

2022-06-01 17:53 UTC, lucasrendo approved these changes

2022-06-01 17:53 UTC, lucasrendo commented on src/Components/SuperAdmins/index.js
> +      alert(`Super admin ${id} is going to be deleted`);
Este alert no estaria haciendo nada ya que para esta linea de codigo ya se borro el super-admin

2022-06-01 17:55 UTC, merged

2022-06-04 00:19 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/List/superadmin-list.jsx
> +import Styles from '../List/superadminlist.module.css';
Normalmente usamos variables que comienzan con mayusculas para los componentes. En este caso deberia ser `styles`

2022-06-04 00:19 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/List/superadmin-list.jsx
> +import Styles from '../List/superadminlist.module.css';
Normalmente usamos variables que comienzan con mayusculas para los componentes. En este caso deberia ser `styles`

2022-06-04 00:28 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/List/superadmin-list.jsx
> +import React from 'react';
Este componente no se esta usando en ningun lado

2022-06-04 00:28 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/List/superadmin-list.jsx
> +import React from 'react';
Este componente no se esta usando en ningun lado

2022-06-04 00:28 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/index.js
> +  useEffect(async () => {
La funcion dentro del useEffect no puede ser asincronica

2022-06-04 00:28 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/index.js
> +  useEffect(async () => {
La funcion dentro del useEffect no puede ser asincronica

2022-06-04 00:29 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/index.js
> +    saveSuperadmins([...superadminsList.filter((ListItem) => ListItem._id !== id)]);
Aca deberias validar que la respuesta del back es exitosa antes de guardar la data

2022-06-04 00:29 UTC, BaltazarCortina1 commented on src/Components/SuperAdmins/index.js
> +    saveSuperadmins([...superadminsList.filter((ListItem) => ListItem._id !== id)]);
Aca deberias validar que la respuesta del back es exitosa antes de guardar la data