BaSP-TG-36: admin list
BaSP-m2022/balti-trackgenix-app pull request #30
Opened 2022-06-08 02:27 UTC by nicomicheletti

2022-06-08 17:26 UTC, FranGutierrez approved these changes
Looks and works correctly!

2022-06-08 19:53 UTC, MatiasJoaquinReynoso requested changes
Hello Nico, reviewing your pr I can say that the CRUD methods works correctly !!, I only make a few observations.

1- When creating admin there is no redirection (if I press ok in the modal everything is kept on the same page) and if I continue pressing the save button with the same validations the same user is created many times

2- When deleting an id it does not send me a modal for confirmation of delete from user

2022-06-09 11:58 UTC, MatiasJoaquinReynoso approved these changes

2022-06-10 16:58 UTC, Julian25 approved these changes

2022-06-10 16:59 UTC, merged

2022-06-13 06:06 UTC, BaltazarCortina1 commented on src/Components/Admins/index.js
> +      setIsLoading(false);
Sigue faltando validar la respuesta.

2022-06-13 06:06 UTC, BaltazarCortina1 commented on src/Components/Admins/index.js
> +          className={styles.LinkReset}
Esto ya no es necesario, solo la ruta

2022-06-13 06:07 UTC, BaltazarCortina1 commented on src/Components/Admins/index.js
> +  const config = [
Esto ya no es necesario aca