BaSP-TG-44: Employees Form
BaSP-m2022/balti-trackgenix-app pull request #32
Opened 2022-06-08 02:32 UTC by gc796

- Used form component
- Used button component
- Set list and form in different screens
- Function inside useEfect is not asynchronous

2022-06-08 18:07 UTC, FranGutierrez requested changes
En el formulario de crear faltan campos, por eso aparece el error de missing data

2022-06-08 18:07 UTC, FranGutierrez commented on src/routes.js
> +          <Route exact path={'/employees/form'} component={Form} />
Falta añadir la ruta para abrir el form de editar

2022-06-08 23:04 UTC, FranGutierrez approved these changes

2022-06-11 17:39 UTC, BaltazarCortina1 commented on src/Components/Employees/Form/index.js
> +  const [employeeList, setEmployeeList] = useState();
Cambiemosle el nombre a employee, porque ya no es una lista

2022-06-11 20:50 UTC, Julian25 approved these changes

2022-06-11 20:57 UTC, MatiasJoaquinReynoso approved these changes
Everything works correctly !

2022-06-11 21:00 UTC, merged

2022-06-13 04:17 UTC, BaltazarCortina1 commented on src/Components/Employees/Form/index.jsx
> +  const [isAdding, setIsAdding] = useState(false);
Este state solo lo usas para mostrar el modal, no se deberia llamar showModal o algo asi?

2022-06-13 04:18 UTC, BaltazarCortina1 commented on src/Components/Employees/Form/index.jsx
> +      if (id) {
El if deberia ir fuera del try

2022-06-13 04:18 UTC, BaltazarCortina1 commented on src/Components/Employees/Form/index.jsx
> +    });
Aca vendria mejor un map en lugar de un forEach, asi no hace falta que declares el array vacio antes y que vayas pusheando los elementos