BaSP-TG-38: Project - List implemented
BaSP-m2022/balti-trackgenix-app pull request #33
Opened 2022-06-08 02:41 UTC by lautaro23

Work done on this branch:

Implemented List component in Project
Implemented Loading component in Project
Implemented Button component in Project

2022-06-08 17:23 UTC, FranGutierrez requested changes

2022-06-08 17:23 UTC, FranGutierrez commented on src/Components/Projects/index.js
>    }, []);
Eliminar este fetch, dentro del useEffect mas abajo esta realizado correctamente

2022-06-08 21:13 UTC, FranGutierrez approved these changes

2022-06-11 21:54 UTC, Julian25 approved these changes

2022-06-11 22:00 UTC, negrojcb approved these changes

2022-06-11 22:02 UTC, merged