BaSP-TG-53: Implement redux on form shared component and tasks form
BaSP-m2022/balti-trackgenix-app pull request #36
Opened 2022-06-14 00:57 UTC by lucasrendo

- Shared form component now receives redux state instead of react state in itemData
- InputValues prop changed to action prop which receives an arrow function that in turn receives input values as parameter and pass it to the action creator
- Change all shared React states on form index to global redux states imported from the store
- All fetch functions were moved from the index to a separate file to be reusable and everything is handled by redux

2022-06-14 01:30 UTC, Julian25 submitted a review, later dismissed
Excelente!!!

2022-06-14 01:38 UTC, GonzaloBracamonte requested changes
Al parecer el codigo esta todo bien escrito pero no funcionan el selector de employees y el selector de projects

2022-06-14 01:38 UTC, BaltazarCortina1 requested changes

2022-06-14 01:38 UTC, BaltazarCortina1 commented on src/Components/Shared/Form/Form.jsx
> -import { useState, useEffect } from 'react';
Mantengamos el form como estaba, sin usar redux, asi tenemos que hacer menos cambios en los otros componentes.

2022-06-14 11:35 UTC, GonzaloBracamonte submitted a review, later dismissed
La aplicacion ya funciona correctamente y el codigo se ve bien, excelente!

2022-06-14 12:47 UTC, Julian25 requested changes

2022-06-14 12:47 UTC, Julian25 commented on src/redux/Task/reducer.js
> +  GET_SINGLE_TASK_FULFILLED,
cambiar fullfilled por success

2022-06-14 12:51 UTC, CorinaArreguez approved these changes

2022-06-14 19:08 UTC, GonzaloBracamonte approved these changes

2022-06-15 15:03 UTC, Julian25 approved these changes

2022-06-16 14:10 UTC, BaltazarCortina1 approved these changes

2022-06-17 02:32 UTC, MatiasJoaquinReynoso requested changes
The project and employee lists from Project entities dont load the information when you open the deploy for first time

2022-06-17 03:36 UTC, MatiasJoaquinReynoso approved these changes
Fix bugs ! everything works ok :)

2022-06-17 03:37 UTC, merged

2022-06-18 20:28 UTC, BaltazarCortina1 commented on src/.vscode/settings.json
> +{
Este archivo no deberia estar aca

2022-06-18 20:38 UTC, BaltazarCortina1 commented on src/Components/Tasks/Form/index.jsx
> +    projectList.forEach((project) =>
Podemos cambiar este `forEach` por un `map`