BaSP-TG-56: redux and modal implemented on projects list
BaSP-m2022/balti-trackgenix-app pull request #38
Opened 2022-06-14 12:40 UTC by Julian25

Work done on this branch: 
- Ract states were replaced by redux states
- Fetchs are done trough redux middleware thunk
- Confirmation modal brefore deleting a project was implemented
- Informational modal after deleting a project was implemented

2022-06-14 13:03 UTC, GonzaloBracamonte approved these changes
La aplicacion funciona y el codigo se ve bien, trabajo genial!

2022-06-14 17:49 UTC, GonzaloBracamonte approved these changes

2022-06-14 20:54 UTC, CorinaArreguez requested changes
Cambiar el nombre de las constants failed a error

2022-06-14 21:01 UTC, GonzaloBracamonte approved these changes

2022-06-14 21:10 UTC, CorinaArreguez approved these changes

2022-06-14 21:12 UTC, Evelyn-Heredia submitted a review, later dismissed
Approved, modals working!

2022-06-15 00:22 UTC, nicomicheletti approved these changes

2022-06-15 00:23 UTC, nicomicheletti approved these changes

2022-06-15 00:24 UTC, nicomicheletti commented
Excelente funcionamiento y el código muy claro!

2022-06-15 00:38 UTC, merged

2022-06-18 18:45 UTC, BaltazarCortina1 commented on src/redux/projects/constants.js
> +export const GET_SINGLE_PROJECT_ERROR = 'GET_SINGLE_PROJECT_ERROR';
Estas constants no son necesarias para la lista, lo mismo que las actions y los cases del reducer. Deberian haber estado directamente en la PR del form

2022-06-18 20:08 UTC, BaltazarCortina1 commented on src/redux/projects/thunks.js
> +      dispatch(getProjectsSuccess(data.data));
Falta validar que la respuesta haya sido exitosa

2022-06-18 20:13 UTC, BaltazarCortina1 commented on src/Components/Projects/List/index.jsx
> +    dispatch(getProjects());
No hace falta que te vuelvas a traer los projects, deberias filtrar el que eliminaste de la lista