BaSP-TG-51: Admin redux for form and list
BaSP-m2022/balti-trackgenix-app pull request #40
Opened 2022-06-14 18:01 UTC by FedeBrus64

The redux has been made for both the admin form and list. Also, the modal has been implemented on both components

2022-06-15 14:27 UTC, Julian25 approved these changes

2022-06-15 19:13 UTC, Julian25 requested changes

2022-06-16 13:12 UTC, FedeBrus64 commented on src/Components/Admins/List/index.jsx
> +      <Modal handleClose={() => closeHandler()} isOpen={isAdding} isConfirmation={false}>
Corregido!

2022-06-16 14:30 UTC, Julian25 approved these changes

2022-06-16 14:56 UTC, GonzaloBracamonte approved these changes

2022-06-16 16:38 UTC, Evelyn-Heredia approved these changes
PR approved!

2022-06-16 17:39 UTC, merged

2022-06-18 19:11 UTC, BaltazarCortina1 commented on src/redux/admins/actions.js
> +export const getAdminsError = (message) => ({
Esta action se llama get, pero lo que estas haciendo es cambiar el mensaje

2022-06-18 19:24 UTC, BaltazarCortina1 commented on src/redux/admins/thunks.js
> +      const response_1 = await response.json();
Cambiemos `response_1` por `data`. `response_1` no respeta las buenas practicas para los nombres de variables

2022-06-18 19:26 UTC, BaltazarCortina1 commented on src/redux/admins/thunks.js
> +      dispatch(getAdminsSuccess(response_1.data));
Falta validar si la respuesta fue exitosa o no

2022-06-18 19:28 UTC, BaltazarCortina1 commented on src/Components/Admins/Form/index.jsx
> +    getAdmins();
Necesitas toda la lista de admins en el Form?

2022-06-18 19:29 UTC, BaltazarCortina1 commented on src/Components/Admins/Form/index.jsx
>    };
Esto ya no deberia estar aca, se maneja con el thunk

2022-06-18 19:31 UTC, BaltazarCortina1 commented on src/Components/Admins/Form/index.jsx
> +      setModalMessage('Edit successful');
Tendrias que esperar a ver si se creo correctamente antes de mostrar el mensaje

2022-06-18 19:34 UTC, BaltazarCortina1 commented on src/Components/Admins/List/index.jsx
> +  const message = useSelector((state) => state.admins.message);
No estas usando message

2022-06-18 19:38 UTC, BaltazarCortina1 commented on src/Components/Admins/List/index.jsx
> +    !error && dispatch(updateList([...admins.filter((admin) => admin._id !== id)]));
Esto lo deberias hacer en la action de success del delete

2022-06-18 19:39 UTC, BaltazarCortina1 commented on src/Components/Admins/List/index.jsx
> +  const [isAdding, setIsAdding] = useState(false);
Cambiar el nombre de este state a algo mas descriptivo