BaSP-TG-20: Employee Form
BaSP-m2022/balti-trackgenix-app pull request #5
Opened 2022-05-31 21:36 UTC by GonzaloBracamonte

Connect app to server.
Develop list component.
Logic for post method.
Logic for put method.

2022-05-31 23:34 UTC, MatiasJoaquinReynoso requested changes
Hola Gonza, revise tu PR como QA y hay cambios a realizar:
1- el metodo PUT no funciona me da error
2- Revisar el checkbox de Is active, porque al crear un usuario con is active en check positivo me devuelve un usuario creado con is active en FALSE
3- Revisar las validaciones de usuario 
![image](https://user-images.githubusercontent.com/101222934/171300407-b003fa73-5036-42a2-8990-d2bc8f3fd88c.png)

Cualquier cosa en q yo puedo estar confundido o si te puedo ayudar en algo estoy a disposicion !

2022-06-02 00:52 UTC, FranGutierrez reviewed
Encontré los mismos errores que Mati

2022-06-02 03:45 UTC, MatiasJoaquinReynoso requested changes
1- el metodo PUT no funciona me da error al clickear en el boton edit
2- metodo POST : Revisar el checkbox de Is active, porque al crear un usuario con is active en check positivo me devuelve un usuario creado con is active en FALSE

2022-06-02 16:20 UTC, MatiasJoaquinReynoso approved these changes
1) Metodo POST: anda correcto, el is active funciona correctamente. El DATO de color es que cuando creo el user me manda a una pagina en blanco 
![image](https://user-images.githubusercontent.com/101222934/171676769-0ae53677-20d1-442a-9cee-ae3272742547.png)
2) Metodo PUT funciona correctamente

2022-06-02 18:20 UTC, FranGutierrez approved these changes

2022-06-03 00:09 UTC, Evelyn-Heredia reviewed
Hola Gonza, revise tu PR y encontré algunas fallas que te detallo a continuación:

- El método **POST** funciona, pero sigue mostrándote la página en blanco después de crear el nuevo usuario y es necesario actualizar la página para ver el listado actualizado.

- El método PUT también funciona pero para editar un usuario tenes que completar si o si todos los campos (no sé si eso esta pensado así) además no te muestra ningún modal que indique que el usuario se edito y hay que hacer click sobre 'Employees' para que muestre la lista editada.

2022-06-03 01:42 UTC, Evelyn-Heredia approved these changes
POST and PUT methods working!

2022-06-03 02:00 UTC, merged

2022-06-04 01:23 UTC, BaltazarCortina1 commented on src/Components/Employees/AddItem/AddEmployee.js
> +        isActive: isActiveInput.isActive
`isActive` ya es un boolean, no tiene una prop `isActive`

2022-06-04 01:25 UTC, BaltazarCortina1 commented on src/Components/Employees/AddItem/AddEmployee.js
> +        addEmployee(responseJson.data);
Aca deberias validar que la respuesta del back es exitosa antes de guardar la data

2022-06-04 01:27 UTC, BaltazarCortina1 commented on src/Components/Employees/Form/EmployeesForm.js
> +import React, { useState } from 'react';
Los dos formularios son practicamente iguales, podrias reutilizar el mismo componente

2022-06-04 01:28 UTC, BaltazarCortina1 commented on src/Components/Employees/Form/EmployeesForm.js
> +    });
Al editar correctamente un employee te deberia llevar de nuevo a la lista

2022-06-04 01:29 UTC, BaltazarCortina1 commented on src/Components/Employees/index.js
>        <EmployeesList
El form y la lista deberian estar en pantallas separadas