BaSP-TG-81: implement react-hook-form on tasks
BaSP-m2022/balti-trackgenix-app pull request #55
Opened 2022-06-20 23:57 UTC by lucasrendo

- Eliminate Form component and implement Select and Input components alongside react-hook-form
- Fix minor errors on the entity requested by Balti and a few i found while updating the code

2022-06-21 19:54 UTC, Julian25 submitted a review, later dismissed

2022-06-21 20:31 UTC, lautaro23 approved these changes

2022-06-21 22:18 UTC, MatiasJoaquinReynoso requested changes
All buttons works ok ! but a some things to check:

There is no style consistency between title and description:
In Title the error is a red message while description has an error modal. Check the validations between them because on the server, description is not required but on the vercel test the form requires me to complete description input.

2022-06-24 23:17 UTC, MatiasJoaquinReynoso approved these changes
all works correctly !

2022-06-24 23:20 UTC, merged

2022-06-27 03:39 UTC, BaltazarCortina1 commented on src/Components/Tasks/Form/index.jsx
> +    console.log(data);
Quedo un console.log