BaSP-TG-79: implemented React hook form on employees
BaSP-m2022/balti-trackgenix-app pull request #56
Opened 2022-06-21 00:43 UTC by Julian25

Work done on this Branch:

- Updated employees Form using React Hook Form library
- Created the necessary validations required for each type of input

2022-06-21 16:29 UTC, lucasrendo reviewed
- All routes should now be changed to absolute routes
- In actions, create employee should be addEmployee
- In employee actions: getSingleEmployeesError should receive error as parameter instead of message. Same for deleteEmployeeError (segun balti)
- El catch de editEmployee pasa un error.toString(), eso esta bien?
- No se si seria necesario hacer un resetMessage() adentor de los thunks si ya lo hiciste afuera en el form

2022-06-21 16:29 UTC, lucasrendo commented on src/Components/Employees/Form/index.jsx
> +    .pattern(/^[a-zA-Z]+$/)
Se podria agregar whitespace para los nombres compuestos

2022-06-21 16:29 UTC, lucasrendo commented on src/Components/Employees/Form/index.jsx
> +    .pattern(/^[a-zA-Z]+$/)
Se podria agregar un espacio para apellidos compuestos y el simbolo ' para apellidos que lo lleven, pero evitando que se pueda solo poner el simbolo '

2022-06-21 16:29 UTC, lucasrendo commented on src/Components/Employees/Form/index.jsx
> +  assignedProjects: Joi.string().label('Project').required().messages({
This field should be optional and no validations should be triggered when empty

2022-06-21 16:29 UTC, lucasrendo commented on src/Components/Employees/Form/index.jsx
> +    reValidateMode: 'onBlur',
should be mode: 'OnBlur'

2022-06-21 16:29 UTC, lucasrendo commented on src/Components/Employees/Form/index.jsx
> +  const submitHandler = async (data) => {
submit handler no es asincronico

2022-06-21 16:29 UTC, lucasrendo commented on src/Components/Employees/Form/index.jsx
> +            type={'select'}
no longer needed

2022-06-21 16:29 UTC, lucasrendo commented on src/redux/employees/reducer.js
> +        isLoading: false,
En pending esta bien que sea true el loading. Si no es necesario mostrar el loading se deberia eliminar por completo esta linea ya que se encuentro por default en false el isLoading

2022-06-21 16:29 UTC, lucasrendo commented on src/redux/employees/thunks.js
>  const resource = `${process.env.REACT_APP_API_URL}/employees`;
resource should be called url

2022-06-21 22:34 UTC, CorinaArreguez approved these changes

2022-06-21 22:44 UTC, lautaro23 approved these changes

2022-06-22 00:26 UTC, lucasrendo approved these changes

2022-06-22 00:26 UTC, lucasrendo commented on src/Components/Employees/List/index.jsx
>  import { getEmployees, deleteEmployees } from '../../../redux/employees/thunks';
Update this route to absolute path

2022-06-22 02:37 UTC, MatiasJoaquinReynoso requested changes
OPS ! SOMETHIN WRONG !
![image](https://user-images.githubusercontent.com/101222934/174931415-2d407c56-9df6-4f38-a9df-b20559ceda2b.png)

2022-06-22 02:38 UTC, MatiasJoaquinReynoso approved these changes
Fix bugs, all works correctly, but need to fix email repeat from validations server. 
BALTI SIGNAL PLEASE !

2022-06-22 02:40 UTC, merged