BaSP-TG-75: Super Admin Form
BaSP-m2022/balti-trackgenix-app pull request #57
Opened 2022-06-21 15:47 UTC by FedeBrus64

Form for super admin implemented using react hook forms. All methods seem to work correctly. Still, let me know if anything happens.
What has been done:
- Return changed. It no longer returns the form shared component. Instead of that, it returns a form I have created and styled.
- All the fields are validated with the Joi library.
- The reducer for super admin has been updated and it no longer returns the id

2022-06-21 22:07 UTC, Julian25 requested changes
No se sii ya lo viste, pero por las dudas te recuero que la carpeta SuperAdmin en redux esta mal escrita

2022-06-22 01:55 UTC, lucasrendo requested changes
- SuperAdmins folder in redux should be _SuperAdmins_ not _Super Admins_
- Validar en thunks que las respuestas del servidor sean exitosas
- Actualizacion de la lista despues de borrar item deberia hacerse dentro del reducer: borrar constante UPDATE_LIST, funcion updateList y redux action relacionada
- Cambiar rutas relativas por rutas absolutas
- getSingleSuperAdminSuccess recibe como parametro body, cambiar a data el nombre (es la convencion)
- Add y edit superAdmin success reciben como parametro superAdmin, tienen que recibir parametro de nombre data por convencion
- En el reducer a veces se setea una key de nombre modal en varios cases del switch, eliminarla ya que no hay ningun estado con ese nombre en initialState
- GET_SUPER_ADMIN deberia ser GET_SUPER_ADMINS
- Hay 2 acciones que ahcen lo mismo: superAdminMessage y resetSuperAdmin. Borrar la primera y dejar el reset (recordar borrar case en el reducer, constante y action)
- getSuperAdmin y deleteSuperAdmin en thunks no tiene validacion if-else en el caso que haya un error que no sale por el catch (como un 404)
- Es necesario el resetMessage en thunks?

2022-06-22 01:55 UTC, lucasrendo commented on src/Components/SuperAdmins/Form/index.jsx
>    // const resource = '/super-admin';
Delete comment

2022-06-22 01:55 UTC, lucasrendo commented on src/Components/SuperAdmins/Form/index.jsx
>    const message = useSelector((state) => state.superAdmins.message);
Delete useState for inputValues

2022-06-22 01:55 UTC, lucasrendo commented on src/Components/SuperAdmins/Form/index.jsx
> -        <Loading />
El condicional para mostrar el Loading y el componente mismo no deberian borrarse

2022-06-22 01:55 UTC, lucasrendo commented on src/Components/SuperAdmins/Form/index.jsx
> +        <div className={styles.textContainer}>
No envolver los inputs en divs

2022-06-22 01:55 UTC, lucasrendo commented on src/Components/SuperAdmins/Form/index.jsx
> +          <Button>Okay</Button>
Texto de los botones deberian estar alineados con los textos de los botones en los formularios de las otras entidades y alinear botones a la derecha

2022-06-22 01:55 UTC, lucasrendo commented on src/Components/SuperAdmins/Form/super-admins.module.css
> +  align-self: center;
text-align: right es lo que deberia tener

2022-06-22 21:42 UTC, Julian25 requested changes

2022-06-22 22:59 UTC, Julian25 approved these changes

2022-06-23 10:18 UTC, lucasrendo reviewed
Cambios que quedaron pendientes
- En la lista de superAdmins siguen estando las rutas relativas
- La actualizacion de lista sigue en list
- getSuperAdminSuccess sigue recibiendo superAdmins en vez de data
- Los inputs siguen envueltos en div que no es necesario
- El boton cancel deberia decir Back

2022-06-23 19:37 UTC, lautaro23 approved these changes

2022-06-24 18:19 UTC, negrojcb approved these changes

2022-06-24 18:21 UTC, Julian25 approved these changes

2022-06-24 20:04 UTC, lucasrendo approved these changes

2022-06-24 20:09 UTC, merged

2022-06-27 02:43 UTC, BaltazarCortina1 commented on package.json
> +    "yup": "^0.32.11"
La libreria yup no es necesaria. Estamos usando joi