BaSP-TG-82: Time Sheets Form
BaSP-m2022/balti-trackgenix-app pull request #58
Opened 2022-06-21 15:51 UTC by FedeBrus64

Form for time sheets created using react hook forms.
What has been done:
- The form shared component has been replaced with a form I created and styled myself.
- Validations have been implemented using Joi library

2022-06-22 21:50 UTC, Julian25 requested changes

2022-06-22 21:50 UTC, Julian25 commented on src/Components/TimeSheets/Form/index.jsx
>  import Modal from '../../Shared/Modal/Modal';
aca y en todos los casos cambiar por ruta absoluta

2022-06-22 21:50 UTC, Julian25 commented on src/Components/TimeSheets/Form/index.jsx
>  import { getTasks } from '../../../redux/Task/thunks';
usar ruta absoluta

2022-06-22 21:50 UTC, Julian25 commented on src/Components/TimeSheets/Form/index.jsx
> +    reValidateMode: 'onChange',
cambiar revalidateMode por mode

2022-06-22 22:58 UTC, Julian25 approved these changes

2022-06-23 10:43 UTC, lucasrendo reviewed
- en redux constants GET_TIMESHEET es GET_TIMESHEETS
- en redux constants eliminar updateModal
- en redux actions y thunks getTimesheet y sus varaciones es getTimesheets
- Borrar updateList en redux actions
- Borrar const resource linea 21 timesheets thunks
- deleteTimesheet no tiene validacion del lado del try en el thunks
- cambiar rutas en list a absolutas
- Eliminar constante resource de list en timesheets
- Eliminar la linea de updateList en la funcion de confirmation en el list. Ese codigo deberia realizarse dentro del acton de getTimesheetsSuccess

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +  task: Joi.string().label('Task').required().messages({
This is not required

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
>    const [isAdding, setIsAdding] = useState(false);
Este estado no es necesario, hay una action en redux que maneja el estado del modal, se puede borrar este estado o el estado de redux, lo que sea mas conveniente

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +    mode: 'onChange',
mode es onBlur

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +      date: timesheet.date.substring(0, 10),
validar que date existe antes de hacer substring

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +          <div className={styles.textContainer}>
Los divs no son necesarios, recordar que el input se renderiza como
<div>
    ...estructura html del input
</div>

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +              type={'select'}
esta prop ya no se usa

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +              type={'select'}
esta prop ya no se usa

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +              required={false}
esta prop ya no se usa

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +              type={'select'}
esta prop ya no se usa

2022-06-23 10:43 UTC, lucasrendo commented on src/Components/TimeSheets/Form/index.jsx
> +              Cancel
El texto deberia ser Back, no Cancel

2022-06-23 19:43 UTC, lautaro23 approved these changes

2022-06-24 03:40 UTC, MatiasJoaquinReynoso requested changes
Request changes: error message from ROLE input have a error and review these validations 
The message should be: "Role" must be one of [DEV, QA, PM, TL]"
![image](https://user-images.githubusercontent.com/101222934/175457401-16f13616-9a22-4393-9834-11ce91e633da.png)

2022-06-24 03:57 UTC, MatiasJoaquinReynoso approved these changes
Bugs fixed !

2022-06-24 04:06 UTC, merged