BaSP-TG-73: Implement react-hook-form on admins
BaSP-m2022/balti-trackgenix-app pull request #60
Opened 2022-06-21 22:45 UTC by CorinaArreguez

-Update Admin Form using React Hook Form library.
-Create the necessary validations required for each type of input.
-Change response_1 to data.
-Validate that the response was successful in thunks.
-Set modal message with redux.
-Update list in case delete admin success.

2022-06-21 23:45 UTC, Julian25 requested changes

2022-06-21 23:45 UTC, Julian25 commented on src/Components/Admins/Form/index.jsx
> +      dispatch(updateAdmin(data, id));
cambiar updateAdmin por editAdmin

2022-06-21 23:45 UTC, Julian25 commented on src/Components/Admins/Form/index.jsx
> +          required={false}
ya no necesitas el required=false

2022-06-21 23:45 UTC, Julian25 commented on src/Components/Admins/Form/index.jsx
> -import Modal from '../../Shared/Modal/Modal';
cambiar rutas relativas por rutas absolutas

2022-06-21 23:45 UTC, Julian25 commented on src/Components/Admins/Form/index.jsx
> +      .pattern(/^[a-zA-Z ]+$/)
agregar un espacio para nombres compuestos

2022-06-21 23:45 UTC, Julian25 commented on src/Components/Admins/Form/index.jsx
> +      .pattern(/^[a-zA-Z ]+$/)
agregar espacio para apellidos compuestos

2022-06-21 23:45 UTC, Julian25 commented on src/redux/admins/thunks.js
>        dispatch(updateAdminError(error.toString()));
sacar el ".toString()"

2022-06-22 01:24 UTC, Julian25 approved these changes

2022-06-22 19:42 UTC, Julian25 approved these changes

2022-06-23 11:04 UTC, lucasrendo approved these changes
- Cuidado en las hojas de estilo de los modulos, todo los estilos que no se aplican en el jsx de admin no son necesarios. Cuando importamos modulos como Button o Input tambien estamos importando los estilos que ya tienen aplicados por lo que no es necesario reescribirlos en la hoja de estilo que esta importando estos componentes

Hay algunas correcciones menores en la hoja de estilo pero fuera de eso la estandarizacion del codigo y las correcciones correspondientes de la semana pasada sobre esta entidad estan hechas perfectamente! laburazo

2022-06-23 19:20 UTC, merged

2022-06-27 01:53 UTC, BaltazarCortina1 commented on src/redux/admins/thunks.js
> +        return data.data;
No hace falta retornar la data