BaSP-TG-96: add icons and details to the footer
BaSP-m2022/balti-trackgenix-app pull request #67
Opened 2022-06-27 19:37 UTC by lautaro23

- Add linkedin and github icons.
- Add a little text below the icons

2022-06-27 23:26 UTC, FranGutierrez approved these changes
El efecto de hover es diferente al de los otros iconos

2022-07-06 11:44 UTC, lucasrendo requested changes
Se crearon nuevas clases para los SVG y tienen inconsistencias en el estilo del hover. Seria mas limpio y practico borrar las clases creadas y aplicarle a los nuevos iconos las ya existentes para los otros iconos

2022-07-07 16:44 UTC, lucasrendo approved these changes

2022-07-07 22:13 UTC, Evelyn-Heredia approved these changes
PR approved! Just a little detail; footer seems to be too high with regard to the whole app design. However, it matches Figma's design!

2022-07-07 22:23 UTC, merged