TG-92: Readjustment of the routes
BaSP-m2022/balti-trackgenix-app pull request #77
Opened 2022-07-06 02:33 UTC by nicomicheletti

2022-07-07 18:35 UTC, CorinaArreguez commented on src/routes/auth.jsx
> +import register from 'Components/Auth/RegisterForm';
register tiene que ir con mayúscula: Register.

2022-07-08 00:25 UTC, lucasrendo requested changes
- In the register file there is a '/login' route that should be updated to '/auth/login'
- If i use an incorrect employee i get an empty modal while loading and then a whitescreen from which i cannot come back without reloading the page
- The page home should not be the login. It should be the home.

2022-07-08 00:25 UTC, lucasrendo commented on src/routes/index.jsx
> +          <Redirect to="/auth" />
paths are not exact and the redirect does not redirect anywhere as it has the same path as the route component

2022-07-08 00:25 UTC, lucasrendo commented on src/routes/superAdmins.jsx
> +        <Route path="/superadmins" component={superAdmin} />
route should be exact and other routes should be added to establish conventions (other routes can be commented)

2022-07-08 16:29 UTC, lucasrendo approved these changes

2022-07-08 18:52 UTC, GonzaloBracamonte approved these changes
Looks good, nice job!

2022-07-08 18:52 UTC, GonzaloBracamonte commented on src/routes/superAdmins.jsx
> +export default superAdmin;
Creo que deberia ser SuperAdmin para mantener una consistencia con los demas controladores de rutas

2022-07-08 23:04 UTC, merged