BaSP-TG-105: Update super admin front-end
BaSP-m2022/balti-trackgenix-app pull request #78
Opened 2022-07-07 23:00 UTC by lautaro23

- [ ] -Adapt form styles acording to figma

- [ ] -Move  list and form logics to new routes accessible only to Super Admins

2022-07-16 22:58 UTC, lucasrendo requested changes
- Old components should not be modified at all. This must be taken back to the way the are in master
- Folder for the entity components is SuperAdmin without the s

All thunks, states and actions should come from the super admin redux files, not admin or employee. If there's any need to modify the reducer of super admin or add something that's currently in another reducer that's what should be done.

For example, in the admin reducer i think there is currently the action to store the admin received from the api when the thunk getSingleSuperAdmin is dispatched. That's probably no longer going to be used in that reducer so you can either copy it or move it entirely to the super admin reducer to use for the edit form, but it's a superadmin action, that's why it should be on the super admin reducer

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/AdminList.js
> +import { deleteEmployees, getEmployees } from 'redux/thunks/admin';
this causes the fetching errors, the thunks is the one of superAdmin, not admin

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/AdminList.js
> +import { resetMessage } from 'redux/employees/actions';
Use the resetMessage from superadmin reducer

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/AdminList.js
> +  const message = useSelector((state) => state.admins.message);
all states should be from superAdmin reducer

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/AdminList.js
> +  const [showModal, setShowModal] = useState(false);
global reducer has a state to handle the modal across the whole application, that's the one that should be used

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/AdminList.js
> +    dispatch(getEmployees());
should be a list of admins, not employees

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/AdminList.js
> +    dispatch(deleteEmployees(id));
should delete admin, not employee

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/AdminList.js
> +  const serverPath = '/admin';
this variable is only used once, it can be deleted and the value used directly on the list prop

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +import { addEmployee, editEmployees, getSingleEmployee } from 'redux/thunks/admin';
the thunks used here is the one from super admin not admin

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +import { resetAdmin, resetMessage } from 'redux/admins/actions';
use super admin actions

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +  const message = useSelector((state) => state.admins.message);
use super admin states

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +  const [showModal, setShowModal] = useState(false);
use global reducer modal toggler

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +  });
use .label() to set custom field name when error is shown. For example firstName: joi.string().label('First Name')

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +      password: ''
shouldn't be here an isActive: true as default? even though it's not an input of the form there's a path for that value on the schema that should be set to true on creation

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +    id && dispatch(getSingleEmployee(id));
use getSingleAdmin() action

2022-07-16 22:58 UTC, lucasrendo commented on src/Components/SuperAdmins/CreateAdmin.js
> +        <Input
this input is set to true on creation automatically, there's no need for this component

2022-07-17 01:17 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/AdminList.js
> +import { deleteEmployees, getEmployees } from 'redux/thunks/admin';
Done

2022-07-17 01:17 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/AdminList.js
> +    dispatch(getEmployees());
Done

2022-07-17 01:23 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/AdminList.js
> +    dispatch(deleteEmployees(id));
Done

2022-07-17 01:23 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/AdminList.js
> +  const serverPath = '/admin';
Done

2022-07-17 01:26 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +import { addEmployee, editEmployees, getSingleEmployee } from 'redux/thunks/admin';
Done

2022-07-17 01:30 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +  const message = useSelector((state) => state.admins.message);
Done

2022-07-17 01:31 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +    id && dispatch(getSingleEmployee(id));
Done

2022-07-17 01:32 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +      password: ''
You´re right, the change its done

2022-07-17 01:33 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +        <Input
Done

2022-07-17 01:34 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +  });
Done

2022-07-17 02:09 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/AdminList.js
> +import { resetMessage } from 'redux/employees/actions';
Done

2022-07-17 02:24 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +import { resetAdmin, resetMessage } from 'redux/admins/actions';
Done

2022-07-17 02:27 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/AdminList.js
> +  const message = useSelector((state) => state.admins.message);
There is only one state that must be stabilized, which is the state of the list so that it shows the admins. 
The rest are changed

2022-07-17 03:12 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/CreateAdmin.js
> +  const [showModal, setShowModal] = useState(false);
Done

2022-07-17 03:16 UTC, GonzaloBracamonte commented on src/Components/SuperAdmins/AdminList.js
> +  const [showModal, setShowModal] = useState(false);
Done

2022-07-18 12:58 UTC, lucasrendo commented on src/Components/SuperAdmin/CreateAdmin.js
> +    return () => dispatch(resetSuperAdmin());
This looks like you fetch and store an admin and then delete a super admin from the store. The reset should be resetAdmin

2022-07-18 12:58 UTC, lucasrendo commented on src/Components/SuperAdmin/CreateAdmin.js
> +    reset(superAdmin);
The form is to edit an admin so this state should be called admin

2022-07-18 12:58 UTC, lucasrendo commented on src/redux/superadmin/reducer.js
> +  superAdmin: undefined,
in here should go 'admin'.

2022-07-18 12:58 UTC, lucasrendo commented on src/redux/superadmin/reducer.js
> +  list: [],
This list is to store admin's list. The list of admins should go here and the list state in the component should point to this state. Also the action to retrieve admins should also be in the superAdmin's

2022-07-18 13:53 UTC, GonzaloBracamonte commented on src/Components/SuperAdmin/CreateAdmin.js
> +    return () => dispatch(resetSuperAdmin());
Done

2022-07-18 13:55 UTC, GonzaloBracamonte commented on src/redux/superadmin/reducer.js
> +  superAdmin: undefined,
Done

2022-07-19 23:00 UTC, GonzaloBracamonte commented on src/redux/superadmin/reducer.js
> +  list: [],
Done

2022-07-20 01:14 UTC, lucasrendo commented on src/routes/index.jsx
> +import PrivateRoute from './privateRoute';
Use PrivateRoute as file name as it's a component

2022-07-20 01:51 UTC, GonzaloBracamonte commented on src/routes/index.jsx
> +import PrivateRoute from './privateRoute';
Done

2022-07-20 04:12 UTC, lucasrendo approved these changes

2022-07-20 05:07 UTC, MatiasJoaquinReynoso requested changes
Hi lucas i miss you brother but i have bad news:

1) LOGIN bug: When I fill in the password field with invalid data the following modal pops up 
![image](https://user-images.githubusercontent.com/101222934/179900713-2ec2c89a-28f0-49b5-a8ec-bd716111ed01.png)
2) SUPERADMIN PUT METHOD redirect is it a bug or is it in process?! : 
![image](https://user-images.githubusercontent.com/101222934/179900828-4585beaa-c726-4ba4-97fe-4f3f40cadce3.png)
3) FIRST/LAST NAME ERROR TEXT PLS MODIFY:
![image](https://user-images.githubusercontent.com/101222934/179900996-260997f5-7b7f-40ad-8fea-4ae2799faace.png)
5) COMPLETE LAST NAME WITH INVALID DATA (lastname: 'aaaa') the following modal appears
![image](https://user-images.githubusercontent.com/101222934/179902704-9cd7c10b-64c0-4541-b0bc-552cf2250fd7.png)
6) LENGTH OF THE EMAL DEFORMS THE LIST
![image](https://user-images.githubusercontent.com/101222934/179903170-e65dd670-637a-4752-a93a-460e00185298.png)


btw the rest works correctly (i think) , correct authetifications each role works according their routes. 
The corrections are all aesthetic my only problem is the superadmin edition bug :/

2022-07-22 13:54 UTC, MatiasJoaquinReynoso requested changes
Bugs from put method: when i try to edit something, email error modals appears
![image](https://user-images.githubusercontent.com/101222934/180454092-df237d64-efda-4385-8844-03d918ad3a34.png)

2022-07-23 19:26 UTC, MatiasJoaquinReynoso approved these changes

2022-07-23 21:10 UTC, merged