BaSP-TG-109: Log in form styles corrected
BaSP-m2022/balti-trackgenix-app pull request #79
Opened 2022-07-08 01:16 UTC by Julian25

Work done on this brach:

- Log in form styles where corrected according to figma

2022-07-08 02:33 UTC, lucasrendo requested changes

2022-07-08 02:33 UTC, lucasrendo commented on src/Components/Auth/Login/index.jsx
> +            <h2 className={styles.loginTitle}>Log In</h2>
El titulo deberia quedar por fuera del formulario, semanticamente esto seria incorrecto

2022-07-10 14:03 UTC, lucasrendo approved these changes

2022-07-10 18:58 UTC, MatiasJoaquinReynoso approved these changes

2022-07-10 19:22 UTC, FranGutierrez approved these changes

2022-07-10 19:49 UTC, merged