BaSP-TG-110: update of admin form
BaSP-m2022/balti-trackgenix-app pull request #81
Opened 2022-07-15 14:41 UTC by GonzaloBracamonte

In this PR, the size of the inputs, the color of the background and the form were changed, as well as the addition of a background image. 
The color of the buttons also changed to suit the figma project.

2022-07-23 19:00 UTC, FranGutierrez approved these changes

2022-07-27 13:09 UTC, Julian25 approved these changes

2022-07-27 13:21 UTC, MatiasJoaquinReynoso requested changes
All works ok, but i found a problem on the size of inpunts,
Steps:
1- complete all fields but not first name (empty data)
2- error text appears
3- when i try to complete the first name, the input size changes.

![image](https://user-images.githubusercontent.com/101222934/181257252-26c513df-6cb7-4b51-88b0-b609e439b373.png)

2022-07-27 17:34 UTC, MatiasJoaquinReynoso approved these changes

2022-07-27 17:46 UTC, merged