BaSP-TG-2:  admin list
BaSP-m2022/balti-trackgenix-app pull request #9
Opened 2022-05-31 22:26 UTC by lautaro23

-Connect app to server.
 -Develop list component.
 -Logic for get method.
 -Logic for delete method.

2022-05-31 23:35 UTC, FranGutierrez requested changes
Tenes un archivo css vacio, por eso te tira error el vercel al deployar

2022-05-31 23:39 UTC, FranGutierrez approved these changes

2022-05-31 23:42 UTC, lautaro23 commented
aahh graciaas frann!!

2022-06-01 21:15 UTC, FedeBrus64 approved these changes

2022-06-02 02:33 UTC, MatiasJoaquinReynoso approved these changes
Metodo Get & Del funcionan correctamente

2022-06-02 03:06 UTC, lucasrendo approved these changes

2022-06-02 14:19 UTC, negrojcb approved these changes

2022-06-02 14:49 UTC, merged

2022-06-04 02:00 UTC, BaltazarCortina1 commented on src/Components/Admins/ListItem/ListItem.js
> +        if (response.status !== 200) {
Esta bueno que valides si la request fue exitosa. Pero no hay ningun catch que agarre el error, si el status no es 200 te explota la app

2022-06-04 02:00 UTC, BaltazarCortina1 commented on src/Components/Admins/index.js
> +        setAdmins(response.data);
Aca deberias validar que la respuesta del back es exitosa antes de guardar la data